### ISSUE TITLE
Unable to do binning analysis through `correlation_bins_to_csv`

### ISSUE THREAD

**Issue by kfkq** [SmoQySuite/SmoQyDQMC.jl#11]
Hello, first-time package user here.

I just tried hubbard-chain example, and it gives final result in the term of separated bin. I want to combine them through error analysis (BinningAnalysis), it seems you already provide API function for it, `correlation_bins_to_csv`. 

I got error when calling the function,

the code:
```
using SmoQyDQMC
correlation_bins_to_csv(folder = "hubbard_chain_mu1.96_n-1.07_L24_b8.00-1",
                        correlation = "spin_z",
                        type = "time-displaced",
                        space = "momentum")
```

error message:
```
ERROR: UndefVarError: `_get_num_processes` not defined
Stacktrace:
 [1] correlation_bins_to_csv(; folder::String, correlation::String, type::String, space::String, write_index_key::Bool)
   @ SmoQyDQMC C:\Users\user\.julia\packages\SmoQyDQMC\gOvRz\src\Measurements\binned_data_to_csv.jl:175
 [2] top-level scope
   @ c:\Users\user\Downloads\source codes\DQMC\1d_hubbard\preprocess.jl:3
```

**Comment by cohensbw** [comment]
Thank you for pointing out this issue!
I just released a new version of SmoQyDQMC (v0.2.9 ==> v0.2.10) that should hopefully fix this issues.
I am still working on adding more unit tests to the package, and am grateful for you bring this issue to my attention.
Please let me know if you run into any other problem!

In case you are interested, here is the commit where the fix was implemented:
https://github.com/SmoQySuite/SmoQyDQMC.jl/commit/b2724764526da1e694ffc1c43d7e510e11d0700b
