### ISSUE TITLE
Please provide simple example to do analytical continuation using SmoQyDEAC.jl

### ISSUE THREAD

**Issue by kfkq** [SmoQySuite/SmoQyDQMC.jl#12]
I was not aware you also provide analytical continuation package. Great, thanks!

But I am not familiar with this new technique. Please kindly provide new example in the main SmoQyDQMC.jl package how to do this. 

If I refer to the SmoQyDEAC.jl, [one example file in the package](https://github.com/SmoQySuite/SmoQyDEAC.jl/blob/main/scripts/fermion_greens.jl), it seems i need to do binninganalysis first to get all they key dictionary of jld file, but since the DQMC outputs are in bin file, and only have [id_pairs, correlations, bond_id_pairs, time_displaced] as the key, so I am not sure about the exact step.

Thank you.

**Comment by sandimas** [comment]
Hi kfkq,

For the SmoQyDQMC side, you will need to use [correlation_bins_to_csv(...)](https://smoqysuite.github.io/SmoQyDQMC.jl/dev/api/#SmoQyDQMC.correlation_bins_to_csv) to turn the binaries to .csv format.

I will work on getting making an example for SmoQyDEAC which takes shows how to take those csvs and process them through DEAC with an intermediate script so that not everyone has to reinvent the wheel.

- James

**Comment by sandimas** [comment]
I've added an [example to SmoQyDEAC](https://smoqysuite.github.io/SmoQyDEAC.jl/dev/examples/SmoQyDQMC/) which begins after you've used SmoQyDQMC's correlation_bins_to_csv call for fermion greens functions in momentum space.

There is a script I've added to SmoQyDEAC which can parse binned and unbinned output from SmoQyDQMC. That script can be found [here (SmoQyDQMCloader.jl)](https://github.com/SmoQySuite/SmoQyDEAC.jl/blob/main/scripts/SmoQyDQMCloader.jl). We may move it to a utilities repo later, which will be reflected in that example.

These should be enough to get started without too much consternation.

- James
